### ISSUE TITLE
🌹

### ISSUE THREAD

**Issue by asanpardazzagrosheyrani** [ensdomains/ens-contracts#386]
https://github.com/ethereumfollowprotocol/app/issues/98

**Comment by tayy-i** [comment]
Additional item from the #383 remediation review (pre-existing, surfaced by the codex bot): **cross-projection read coherence on decorated routes** — /v2/permissions reads `permissions_current` and then decorates rows from `name_current` via `load_current_names_by_resource_ids` in a separate SELECT (the two-read pattern established for representative names in PR #96; #383 only added wrapper fields to the existing second read). A Project publish between the reads can make the decoration disagree with the powers row. Same coherence family as this issue's derivation items — resolve together under one read-view/capture-and-revalidate policy rather than per-route patches.
